class_name BgmCatalog
extends RefCounted

const ORDER := [
	"stillness",
	"wave_of_kulangsu",
	"sunny_side_stroll",
	"pocket_stars",
	"moonlit_refrain",
	"seaside_portico_waltz",
	"sanctuary_of_stillness",
	"echoes_under_stone",
	"lantern_route",
	"tower_air",
	"after_the_stage",
	"night_tide_memory",
]


static func ordered_ids() -> PackedStringArray:
	return PackedStringArray(ORDER)


static func build_catalog() -> Dictionary:
	return {
		"stillness": {
			"label": "Stillness",
			"file": "res://resources/audio/music/bgm/Stillness.ogg",
			"tier": "commons",
			"duration": 64.0,
			"location": {
				"ferry_plaza": 0.45,
				"trinity_church": 0.72,
				"bi_shan_tunnel": 0.58,
				"long_shan_tunnel": 0.58,
				"bagua_tower": 0.38,
				"overworld": 0.52,
			},
			"time": {
				"morning": 0.62,
				"afternoon": 0.42,
				"evening": 0.78,
				"night": 1.0,
			},
			"progress": {
				"unknown": 1.0,
				"heard": 0.88,
				"reconstructed": 0.56,
				"performed": 0.34,
				"resonant": 0.38,
			},
			"season": {
				"spring": 0.58,
				"summer": 0.46,
				"autumn": 0.82,
				"winter": 1.0,
			},
			"weather": {
				"clear": 0.72,
				"rain": 0.64,
				"fog": 0.84,
				"wind": 0.42,
			},
			"variants": {},
		},
		"wave_of_kulangsu": {
			"label": "Wave of Kulangsu",
			"file": "res://resources/audio/music/bgm/Wave of Kulangsu.ogg",
			"tier": "commons",
			"duration": 66.0,
			"location": {
				"ferry_plaza": 0.84,
				"trinity_church": 0.34,
				"bi_shan_tunnel": 0.28,
				"long_shan_tunnel": 0.32,
				"bagua_tower": 0.48,
				"overworld": 0.82,
			},
			"time": {
				"morning": 0.66,
				"afternoon": 1.0,
				"evening": 0.62,
				"night": 0.24,
			},
			"progress": {
				"unknown": 0.46,
				"heard": 0.72,
				"reconstructed": 1.0,
				"performed": 0.82,
				"resonant": 0.68,
			},
			"season": {
				"spring": 0.68,
				"summer": 1.0,
				"autumn": 0.58,
				"winter": 0.28,
			},
			"weather": {
				"clear": 0.92,
				"rain": 0.34,
				"fog": 0.42,
				"wind": 0.54,
			},
			"variants": {},
		},
		"sunny_side_stroll": {
			"label": "Sunny Side Stroll",
			"file": "res://resources/audio/music/bgm/Sunny Side Stroll.ogg",
			"tier": "commons",
			"duration": 61.0,
			"location": {
				"ferry_plaza": 0.62,
				"trinity_church": 0.42,
				"bi_shan_tunnel": 0.24,
				"long_shan_tunnel": 0.38,
				"bagua_tower": 0.54,
				"overworld": 0.86,
			},
			"time": {
				"morning": 0.78,
				"afternoon": 1.0,
				"evening": 0.54,
				"night": 0.16,
			},
			"progress": {
				"unknown": 0.34,
				"heard": 0.62,
				"reconstructed": 0.96,
				"performed": 0.86,
				"resonant": 0.72,
			},
			"season": {
				"spring": 0.82,
				"summer": 1.0,
				"autumn": 0.54,
				"winter": 0.18,
			},
			"weather": {
				"clear": 0.94,
				"rain": 0.26,
				"fog": 0.34,
				"wind": 0.46,
			},
			"variants": {},
		},
		"pocket_stars": {
			"label": "Pocket Stars",
			"file": "res://resources/audio/music/bgm/Pocket Stars.ogg",
			"tier": "commons",
			"duration": 58.0,
			"location": {
				"ferry_plaza": 0.48,
				"trinity_church": 0.48,
				"bi_shan_tunnel": 0.36,
				"long_shan_tunnel": 0.42,
				"bagua_tower": 0.72,
				"overworld": 0.58,
			},
			"time": {
				"morning": 0.72,
				"afternoon": 0.64,
				"evening": 0.76,
				"night": 0.58,
			},
			"progress": {
				"unknown": 0.18,
				"heard": 0.34,
				"reconstructed": 0.62,
				"performed": 0.92,
				"resonant": 1.0,
			},
			"season": {
				"spring": 0.84,
				"summer": 0.72,
				"autumn": 0.58,
				"winter": 0.32,
			},
			"weather": {
				"clear": 0.82,
				"rain": 0.34,
				"fog": 0.58,
				"wind": 0.44,
			},
			"variants": {},
		},
		"moonlit_refrain": {
			"label": "Moonlit Refrain",
			"file": "res://resources/audio/music/bgm/Moonlit Tides Save Theme.ogg",
			"tier": "commons",
			"duration": 119.28,
			"location": {
				"ferry_plaza": 0.36,
				"trinity_church": 0.54,
				"bi_shan_tunnel": 0.46,
				"long_shan_tunnel": 0.48,
				"bagua_tower": 0.64,
				"overworld": 0.52,
			},
			"time": {
				"morning": 0.34,
				"afternoon": 0.42,
				"evening": 1.0,
				"night": 0.96,
			},
			"progress": {
				"unknown": 0.28,
				"heard": 0.42,
				"reconstructed": 0.72,
				"performed": 0.94,
				"resonant": 1.0,
			},
			"season": {
				"spring": 0.58,
				"summer": 0.52,
				"autumn": 0.86,
				"winter": 0.78,
			},
			"weather": {
				"clear": 0.78,
				"rain": 0.48,
				"fog": 0.82,
				"wind": 0.36,
			},
			"variants": {},
		},
		"seaside_portico_waltz": {
			"label": "Seaside Portico Waltz",
			"file": "res://resources/audio/music/bgm/Seaside Portico Waltz.ogg",
			"tier": "location",
			"duration": 63.0,
			"location": {
				"ferry_plaza": 1.0,
				"trinity_church": 0.12,
				"bi_shan_tunnel": 0.08,
				"long_shan_tunnel": 0.12,
				"bagua_tower": 0.44,
				"overworld": 0.74,
			},
			"time": {
				"morning": 0.74,
				"afternoon": 1.0,
				"evening": 0.62,
				"night": 0.14,
			},
			"progress": {
				"unknown": 0.44,
				"heard": 0.72,
				"reconstructed": 0.92,
				"performed": 0.84,
				"resonant": 0.68,
			},
			"season": {
				"spring": 0.72,
				"summer": 1.0,
				"autumn": 0.52,
				"winter": 0.16,
			},
			"weather": {
				"clear": 0.92,
				"rain": 0.22,
				"fog": 0.28,
				"wind": 0.48,
			},
			"variants": {},
		},
		"sanctuary_of_stillness": {
			"label": "Sanctuary of Stillness",
			"file": "res://resources/audio/music/bgm/Sanctuary of Stillness.ogg",
			"tier": "location",
			"duration": 67.0,
			"location": {
				"ferry_plaza": 0.14,
				"trinity_church": 1.0,
				"bi_shan_tunnel": 0.42,
				"long_shan_tunnel": 0.34,
				"bagua_tower": 0.18,
				"overworld": 0.18,
			},
			"time": {
				"morning": 0.68,
				"afternoon": 0.54,
				"evening": 0.94,
				"night": 0.88,
			},
			"progress": {
				"unknown": 0.92,
				"heard": 1.0,
				"reconstructed": 0.64,
				"performed": 0.42,
				"resonant": 0.48,
			},
			"season": {
				"spring": 0.58,
				"summer": 0.48,
				"autumn": 0.82,
				"winter": 0.96,
			},
			"weather": {
				"clear": 0.76,
				"rain": 0.58,
				"fog": 0.82,
				"wind": 0.36,
			},
			"variants": {},
		},
		"echoes_under_stone": {
			"label": "Echoes Under Stone",
			"file": "res://resources/audio/music/bgm/Abyssal Echoes.ogg",
			"tier": "location",
			"duration": 194.84,
			"location": {
				"ferry_plaza": 0.08,
				"trinity_church": 0.22,
				"bi_shan_tunnel": 1.0,
				"long_shan_tunnel": 0.68,
				"bagua_tower": 0.24,
				"overworld": 0.12,
			},
			"time": {
				"morning": 0.42,
				"afternoon": 0.58,
				"evening": 0.92,
				"night": 0.88,
			},
			"progress": {
				"unknown": 0.48,
				"heard": 0.84,
				"reconstructed": 1.0,
				"performed": 0.54,
				"resonant": 0.62,
			},
			"season": {
				"spring": 0.48,
				"summer": 0.64,
				"autumn": 0.78,
				"winter": 0.82,
			},
			"weather": {
				"clear": 0.78,
				"rain": 0.62,
				"fog": 0.94,
				"wind": 0.34,
			},
			"variants": {},
		},
		"lantern_route": {
			"label": "Lantern Route",
			"file": "res://resources/audio/music/bgm/Cozy Little Loop.ogg",
			"tier": "location",
			"duration": 161.16,
			"location": {
				"ferry_plaza": 0.14,
				"trinity_church": 0.22,
				"bi_shan_tunnel": 0.42,
				"long_shan_tunnel": 1.0,
				"bagua_tower": 0.18,
				"overworld": 0.24,
			},
			"time": {
				"morning": 0.48,
				"afternoon": 0.86,
				"evening": 0.82,
				"night": 0.54,
			},
			"progress": {
				"unknown": 0.18,
				"heard": 0.66,
				"reconstructed": 0.92,
				"performed": 0.78,
				"resonant": 0.88,
			},
			"season": {
				"spring": 0.62,
				"summer": 0.92,
				"autumn": 0.74,
				"winter": 0.34,
			},
			"weather": {
				"clear": 0.94,
				"rain": 0.42,
				"fog": 0.38,
				"wind": 0.52,
			},
			"variants": {},
		},
		"tower_air": {
			"label": "Tower Air",
			"file": "res://resources/audio/music/bgm/Chromatic Glass Corridor.ogg",
			"tier": "location",
			"duration": 232.84,
			"location": {
				"ferry_plaza": 0.18,
				"trinity_church": 0.26,
				"bi_shan_tunnel": 0.22,
				"long_shan_tunnel": 0.28,
				"bagua_tower": 1.0,
				"overworld": 0.32,
			},
			"time": {
				"morning": 0.62,
				"afternoon": 0.74,
				"evening": 0.88,
				"night": 0.76,
			},
			"progress": {
				"unknown": 0.14,
				"heard": 0.28,
				"reconstructed": 0.88,
				"performed": 0.96,
				"resonant": 1.0,
			},
			"season": {
				"spring": 0.66,
				"summer": 0.78,
				"autumn": 0.72,
				"winter": 0.58,
			},
			"weather": {
				"clear": 0.88,
				"rain": 0.26,
				"fog": 0.56,
				"wind": 0.48,
			},
			"variants": {},
		},
		"after_the_stage": {
			"label": "After the Stage",
			"file": "res://resources/audio/music/bgm/Summer of Piano Island (Chapter 2).ogg",
			"tier": "exclusive",
			"duration": 71.0,
			"location": {
				"ferry_plaza": 0.86,
				"trinity_church": 0.72,
				"bi_shan_tunnel": 0.72,
				"long_shan_tunnel": 0.72,
				"bagua_tower": 0.76,
				"overworld": 0.82,
			},
			"time": {
				"morning": 0.62,
				"afternoon": 0.82,
				"evening": 1.0,
				"night": 0.88,
			},
			"progress": {
				"unknown": 0.0,
				"heard": 0.0,
				"reconstructed": 0.0,
				"performed": 1.0,
				"resonant": 1.0,
			},
			"season": {
				"spring": 0.72,
				"summer": 0.78,
				"autumn": 0.84,
				"winter": 0.54,
			},
			"weather": {
				"clear": 0.86,
				"rain": 0.44,
				"fog": 0.58,
				"wind": 0.42,
			},
			"variants": {},
		},
		"night_tide_memory": {
			"label": "Night Tide Memory",
			"file": "res://resources/audio/music/bgm/Night Tide Motif.ogg",
			"tier": "exclusive",
			"duration": 149.92,
			"location": {
				"ferry_plaza": 0.82,
				"trinity_church": 0.76,
				"bi_shan_tunnel": 0.72,
				"long_shan_tunnel": 0.72,
				"bagua_tower": 0.94,
				"overworld": 0.78,
			},
			"time": {
				"morning": 0.32,
				"afternoon": 0.46,
				"evening": 0.88,
				"night": 1.0,
			},
			"progress": {
				"unknown": 0.0,
				"heard": 0.0,
				"reconstructed": 0.0,
				"performed": 0.0,
				"resonant": 1.0,
			},
			"season": {
				"spring": 0.58,
				"summer": 0.62,
				"autumn": 0.82,
				"winter": 0.74,
			},
			"weather": {
				"clear": 0.84,
				"rain": 0.38,
				"fog": 0.72,
				"wind": 0.34,
			},
			"variants": {},
		},
	}
